baseURL = "https://grey-book-theme-example.onrender.com"
languageCode = "en-us"
title = "Grey Book"
theme = "grey-book"
enableRobotsTXT = true

# for exampleSite only, you need to delete the line below
# when using as the config file for a real site.
themesDir = "../../"

hasCJKLanguage = false

[markup.goldmark.renderer]
# Enables inline rendering of HTML tags in Markdown posts.
unsafe = true

[permalinks]
posts = "/posts/:title/"

[markup.highlight]
guessSyntax = true
style = "monokai"
lineNos = false

[pagination]
pagerSize = 3

[params]
author = "Author"
bio = "Hugo Theme Example Site"
favicon = "images/avatar.jpg"
avatar = "images/avatar.jpg"
openGraphImage = "images/og_image.png"
roundAvatar = true # Default: false
avatarLink = "https://grey-book-theme-example.onrender.com"
# Site Description, used in HTML head
description = "Example Site of the Grey Book Hugo Theme"
keywords = "Hugo, theme, exampleSite"
fediverseCreator = false # Add "@user@example.com" to add a creator tag for Mastodon

# Puts every entry into an invisible rel="me" link on the home page,
# for veryfying your identity with other services
meLinks = [
	"https://fosstodon.org/@usersname"
	]

enableRSS = true
tinyAnalytics = false # The pixel code for your website
insightAnalytics = false # normally "your-getinsights.io-id"

# Set to "production" when in production use, or use
# HUGO_ENV="production" in environment variables.
env = "test" 

home = "" # Default: Home
about = "" # Default: About
archive = "" # Default: Archive
tags = ""  # Default: Tags
subscribe = ""  # Default: Subscribe
olderPosts = "" # Default: Older Posts
newerPosts = "" # Default: Newer Posts
copyright = ""  # Default: © Copyright 2021 ❤ author
title404 = ""  # Default: 404 - Page Not Found
subtitle404 = "" # Default: The content you're looking for doesn't seem to exist.
readMore = ""  # Default: Read More

[params.social]
fediverse = "https://fosstodon.org"
github = "https://www.github.com"
git = "https://codeberg.org"  # for any VCS that's not github
twitter = "https://www.twitter.com"
stackoverflow = "https://www.stackoverflow.com"
facebook = "https://www.facebook.com"
linkedin = "https://www.linkedin.com"


[[params.links]]
name = "Theme Source"
path = "https://github.com/henryleach/grey-book"
